### ISSUE TITLE
Provide valid properties.schema file for Authoring Tool support

### ISSUE THREAD

**Issue by danielstorey** [danielstorey/adapt-backgroundScroll#1]

**Comment by rustysnake** [comment]
Hi Daniel
I'd love to use your background scroll element for the framework. Any rough ideas as of when you think you'd manage to squeeze some time in for making this possible?
Thanks for your great work and have a great day
:-)
Marco

**Comment by danielstorey** [comment]
Hi Marco,
Sorry I haven't managed to get round to this yet. Thanks for your interest and I hope to have an update for you soon!

**Comment by jcarson** [comment]
Daniel,

I would also love to utilize what you have here inside of the authoring tool as I am sure would others. I have had great success with the stack list and flipper and would love to utilize this one as well. Please keep the community posted when you get around to updating this.

big fan,
josh

**Comment by danielstorey** [comment]
Sorry fellas, I don't know what took me so long. I have just provided the required file. I did do it on the fly though so it hasn't been tested. Be great to know if it works. Please close this if you get the chance to verify it. Cheers

**Comment by jcarson** [comment]
Installed fine. however when trying to add the backgroundScroll object i get this error upon opening the component. (see attached)
![error](https://cloud.githubusercontent.com/assets/3779702/21780440/9144b10e-d679-11e6-9b37-150cbc99ade9.jpg)

**Comment by danielstorey** [comment]
Are you getting an error in the console? (press F12 and go to Console tab)
If an error is shown you can click the reference on the right and it will take you to the line in the script that's causing a problem. If you copy the contents into a txt file, upload and let me know the line number that's causing the problem I might be able to provide a diagnosis as I'm not able to test it myself on the AT at the moment. You might need to click the {} button if the script is minified. Hopefully get it sorted soon!
