### ISSUE TITLE
Plugin upload failed

### ISSUE THREAD

**Issue by MarlinsUK** [danielstorey/adapt-backgroundScroll#5]
When I try and upload the plugin using the authoring tool I get the plugin upload failed mesage. Any ideas how to fix?

**Comment by danielstorey** [comment]
Hi @MarlinsUK ,

What version of the framework are you using?

Do you get an error message in the terminal window? (not the browser)

I suspect it's because you're not on v3 of the framework. Please let me know

**Comment by MarlinsUK** [comment]
Ah, I see. I installed the Authoring tool based on [instruction](https://github.com/adaptlearning/adapt_authoring/wiki/Installing-the-Authoring-Tool) - seems that installs v2 of framework. Will try and learn more - do you know if I can upgrade?

**Comment by MarlinsUK** [comment]
OK, based on [this](https://community.adaptlearning.org/mod/forum/discuss.php?d=3585) as i am just gettign started, I am just going to wipe down and start again with fresh install. Thanks for help

**Comment by danielstorey** [comment]
Ok great. I will leave this open for now. Please confirm once you've got it working. Thanks!

**Comment by MarlinsUK** [comment]
Hi, got it working as soon as I upgraded to V4 of the framework. Thanks for your help :)

**Comment by danielstorey** [comment]
Great, thanks for letting me know. Hope it serves you well!
